name: Coverage Report

on:
  push:
    branches: ["main"]

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          amend: true
