name: Test and Coverage Report

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-coverage:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Update to your Go version

      - name: Run Tests and Generate Coverage
        run: |
          # Run tests with coverage
          go test -coverprofile=coverage.out ./...
          # Generate HTML report
          mkdir -p coverage-report/${{ github.event.pull_request.head.sha }}
          go tool cover -html=coverage.out -o coverage-report/${{ github.event.pull_request.head.sha }}/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-report
          # Writing over pr-<pr_number> directory to keep only the latest coverage report for each
          # PR. Also using last commit sha to avoid caching issues.
          destination_dir: coverage/pr-${{ github.event.number }}
          commit_message: "Coverage report for PR ${{ github.event.number }}"

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          # We use `github.event.pull_request.head.sha` variable because in pull requests,
          # `github.sha` variable is the merge commit sha instead of the last commit sha.
          # See: https://github.com/orgs/community/discussions/26325
          message: |
            Coverage report is available [here](https://berkkaraal.com/experiment/coverage/pr-${{ github.event.number }}/${{ github.event.pull_request.head.sha }}/index.html).

            Last commit: ${{ github.event.pull_request.head.sha }}
          comment-tag: execution
