name: Test and Coverage Report

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Update to your Go version

      - name: Run Tests and Generate Coverage
        run: |
          # Run tests with coverage
          go test -coverprofile=coverage.out ./...
          # Generate HTML report
          mkdir -p coverage-report
          go tool cover -html=coverage.out -o coverage-report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-report
          destination_dir: coverage/pr-${{ github.event.number }}
          commit_message: "Coverage report for PR ${{ github.event.number }}"
